version: "3.9"
services:
  # web:
  #   container_name: server
  #   build: ./
  #   command: python3 main.py
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "4000:4000"
  #   env_file:
  #     - .env
  #   links:
  #     - db
  #   depends_on:
  #     - db

  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgrespw